### ISSUE TITLE
Дизайн отображается некорректно. 

### ISSUE THREAD

**Issue by VladKsenobayt** [NonHexagon/Text_to_audio_service#5]
![image](https://user-images.githubusercontent.com/90028811/230291898-1dac8397-5f89-4e37-bc9b-1650452e3b8f.png)

**Comment by VladKsenobayt** [comment]
![image](https://user-images.githubusercontent.com/90028811/230292283-3b0bd4f8-51eb-4f2b-b05c-72a2d6546ca1.png)

**Comment by MikeMarshall36** [comment]
Как выяснилось - это тробла css. На паре будем пробовать чинить. + Вася вроде скинул обновление, но либо я не там смотрю, либо, активный молодой человек, не туда закинул
